# Generated by Django 5.0.9 on 2026-01-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0003_aiservicesetting_auditlog_passwordotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiservicesetting',
            name='api_provider_name',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiservicesetting',
            name='api_key',
            field=models.CharField(max_length=500),
        ),
    ]
