# Generated by Django 5.0.9 on 2026-01-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0004_remove_aiservicesetting_api_provider_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiservicesetting',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI')], default='gemini', max_length=50, unique=True),
        ),
    ]
